# === Netlify Build Configuration for Hugo + Docsy ===
[build]
publish = "userguide/public"
command = "npm run docs-install && npm run build:production"

[build.environment]
GO_VERSION = "1.22.2"
HUGO_VERSION = "0.124.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
GO_IMPORT_PATH = "github.com/greenorbitspace/handbook"

# === Install Hugo Cache Plugin to speed up builds ===
[[plugins]]
package = "netlify-plugin-hugo-cache-resources"

# === Production context ===
[context.production]
command = "npm run docs-install && npm run build:production"